import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import * as images from 'react-icons/gi';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicPath = path.resolve(__dirname, '../', 'public');
const imagesPaths = {
    backgrounds: path.resolve(publicPath, 'backgrounds', 'preprocessed'),
};

const writeImagesPaths = (folderPath: string, category: string) => {
    const imgUrls = fs
        .readdirSync(folderPath)
        .filter((file) => !file.startsWith('.') && !file.startsWith('test'))
        .map((img) => [category, 'preprocessed', img].join('/'));

    const outputPath = path.resolve(
        __dirname,
        '../',
        'public',
        `${category}.json`,
    );
    fs.writeFileSync(outputPath, JSON.stringify(imgUrls));
};
Object.entries(imagesPaths).forEach(([category, folderPath]) =>
    writeImagesPaths(folderPath, category),
);

const icons = {} as Record<string, string>;

Object.keys(images).map((key) => {
    const Component = images[key as keyof typeof images];
    const svgString = renderToStaticMarkup(createElement(Component));

    icons[key.replace('Gi', '')] = svgString
        .replace(
            '<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">',
            '',
        )
        .replace('</svg>', '')
        .replaceAll('"', "'");
});
const iconsObject = {
    template:
        "<svg stroke='#000' fill='#000' stroke-width='0' viewBox='0 0 512 512' height='1em' width='1em' xmlns='http://www.w3.org/2000/svg'>{path}</svg>",
    icons,
};
const iconsPath = path.resolve(__dirname, '../', 'public', 'icons.json');
fs.writeFileSync(iconsPath, JSON.stringify(iconsObject));
const autogeneratedPath = path.resolve(
    __dirname,
    '../',
    'src',
    'constants',
    'autogenerated-do-not-change.json',
);

const spellFiles = fs.readdirSync(path.resolve(publicPath, 'spells'));
interface CalcSizeMap {
    [key: string]: number | CalcSizeMap;
}
const calculatedSizes: CalcSizeMap = {
    iconsSize: fs.statSync(iconsPath).size,
    spells: {},
};
spellFiles.forEach((file) => {
    (calculatedSizes.spells as CalcSizeMap)[file.replace('.msgpack', '')] =
        fs.statSync(path.resolve(publicPath, 'spells', file)).size;
});

fs.writeFileSync(autogeneratedPath, JSON.stringify(calculatedSizes));
